### ISSUE TITLE
[TC-TSTAT-1.1] Step 4, 6 and 7 needs to be updated as per latest test plan in YAML script

### ISSUE THREAD

**Issue by KishokG** [project-chip/matter-test-scripts#360]
## Description:

**- In Step 4, below mentioned attributes needs to be added as per test plan.**
- 0x0052: SHALL be included if and only if TSTAT.S.A0052(SetpointHoldExpiryTimestamp)
- 0x0049: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
- 0x004B: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
 - 0x004C: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
 - 0x004D: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise. 
 - 0x004F: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
 - 0x0051: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.

**- In Step 6, below mentioned Command needs to be added as per test plan.**
- 0x05: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.

**- In Step 6, below mentioned Command needs to be removed as it is not available in test plan.**

![image](https://github.com/user-attachments/assets/eb22d302-0172-4291-a5ae-b0297b3ad26f)

**- In Step 6, PICS needs to be updated for below mentioned Command as per test plan.**

![image](https://github.com/user-attachments/assets/b6f4fc16-ad0a-4ddd-9a2f-9de625d6d2a4)

**- In Step 7, below mentioned Command needs to be removed as it is not available in test plan.**

![image](https://github.com/user-attachments/assets/5a7719bc-a3a3-45e4-a607-4d350c009a06)

**- In Step 7, PICS needs to be updated for below mentioned Command as per test plan.**

![image](https://github.com/user-attachments/assets/a15d6dc1-2887-4d2c-8fa3-dee3ef13c35e)

**Comment by nivi-apple** [comment]
These are not supported -TSTAT.S.F07 = 0. I will set TSTAT.S.A0052=0 in ci-pics-values to fix the attribute 0x0052 

0x0052: SHALL be included if and only if TSTAT.S.A0052(SetpointHoldExpiryTimestamp)
0x0049: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
0x004B: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
0x004C: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
0x004D: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
0x004F: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.
0x0051: SHALL be included if TSTAT.S.F07(MSCH) and SHALL NOT be included otherwise.

**Comment by nivi-apple** [comment]
Uploaded - https://github.com/project-chip/connectedhomeip/pull/35265

**Comment by KishokG** [comment]
Issue fixed
