### ISSUE TITLE
[TC-TSTATS-4.2] - Script Ignores Configured Endpoint

### ISSUE THREAD

**Issue by ZainZhongUL** [project-chip/matter-test-scripts#373]
After side-loading the update from PR 35607, TC-TSTATS-4.2 continues to fail. The test script appears to be ignoring the endpoint specified in the test configuration. The DUT's Thermostat cluster is located on endpoint 5, but the script is still sending test commands to endpoint 1.

We have verified that the test case passes successfully when the Thermostat cluster is located on endpoint 1.

This suggests that the script has a hardcoded endpoint value (endpoint 1), preventing it from adapting to the actual endpoint configuration of the TH.

[Fail-TSTAT-4.2-UI-Python.log](https://github.com/user-attachments/files/17125698/Fail-TSTAT-4.2-UI-Python.log)

**Comment by cecille** [comment]
Test uses a defined parameter for the endpoint rather than using the endpoint from the config. To use the test as-is, you would add --int-arg endpoint:5 or "int-arg": "endpoint:5" to the UI parameters.

Alternately, the test can be corrected to use the endpoint parameter a s expected, which makes more sense to me, IMO. I have a potential fix up here:https://github.com/project-chip/connectedhomeip/pull/35771. However, i would need someone else to validate this as I do not have a TSTAT device with a TSTAT on a different endpoint,
