### ISSUE TITLE
[TC-CNET-4.4] UI manual prompt does not match chip-tool command format

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/matter-test-scripts#46]
## Summary Title: 
[TC-CNET-4.4] UI manual prompt does not match chip-tool command format

## Description:
UI Prompt for step 1 shows as
![Screenshot 2023-10-25 at 5 02 11 PM](https://github.com/project-chip/matter-test-scripts/assets/83772323/484b4b2a-935d-447f-92da-010ac6fce49d)

actual chip-tool usage:
`Usage:
./chip-tool networkcommissioning add-or-update-wi-fi-network Ssid Credentials destination-id endpoint-id-ignored-for-group-commands [--paa-trust-store-path] [--cd-trust-store-path] [--commissioner-name] [--commissioner-nodeid] [--use-max-sized-certs] [--only-allow-trusted-cd-keys] [--trace_file] [--trace_log] [--trace_decode] [--trace-to] [--ble-adapter] [--storage-directory] [--commissioner-vendor-id] [--Breadcrumb] [--timedInteractionTimeoutMs] [--busyWaitForMs] [--suppressResponse] [--repeat-count] [--repeat-delay-ms] [--timeout]
`

**Comment by KishokG** [comment]
@yinyihu-silabs Based on your information, it seems that this step is available in TC-CNET-4.5. It has been updated in VS doc. @manjunath-grl please update the script accordingly.

**Comment by yinyihu-silabs** [comment]
the manual prompt from this step is confusing to user.
in the test plan, it says use `PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID` but example uses `hex`.
if to use `hex`, prompt should add `read networks` to get the hex value.

**Comment by Survensa** [comment]
I agree with you @yinyihu-silabs but we have provided the command as below in VS doc :

./chip-tool networkcommissioning add-or-update-wi-fi-network  hex:**`your network id in hex`** password 1 0

We chose this HEX because, in the future, when all the CNET test cases are automated, and PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID is defined without HEX, it may lead to failures in some CNET test cases for './chip-tool networkcommissioning read networks 1 0' step. 

Also, the reason we do not prefer to 'read network' before the add-or-update step to get HEX is that for the 1st network, we can obtain it through 'read network,' but when it comes to adding the 2nd network, we cannot retrieve the HEX using 'connect network.

@cjandhyala Any comments for this ?

**Comment by Survensa** [comment]
@manjunath-grl Please update the script as per the issue https://github.com/project-chip/matter-test-scripts/issues/49

@yinyihu-silabs Could you please close this issue if you have no concerns about it?
