### ISSUE TITLE
[TC-DA-1.4] and [TC-DA-1.8] - Manual script has to be updated as per VS changes

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/matter-test-scripts#67]
Description:
[TC-DA-1.4] and [TC-DA-1.8] - Manual script has to be updated as per VS changes

**Verification doc reference :** 
https://docs.google.com/spreadsheets/d/13zltSz50GRs_kidvobceEuIT8kAAHSK64ANyWcc3xQI/edit?usp=sharing

**Test-Plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/deviceattestation.adoc#tc-da-1-4-device-attestation-request-validation-error-scenario-dut-commissioner

**Comment by cecille** [comment]
FYI - I have a script for this that should make this test easier. It would still be manual because the script would run outside of the TH, but it might be good to integrate somehow because the setup here is definitely complex and folks have definitely had problems getting this running correctly with all the appropriate flags.

**Comment by Rajashreekalmane** [comment]
Closing this issue as we have a UI manual to validate this test case, and the mentioned SDK PR has been closed
